openapi: 3.0.3
info:
  title: Generated API
  version: "1.0"
paths:
  /todo:
    get:
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListTodoEntity'
    put:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TodoEntity'
      responses:
        "204":
          description: No Content
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TodoEntity'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TodoEntity'
  /todo/{id}:
    get:
      parameters:
      - name: id
        in: path
        required: true
        schema:
          format: int64
          type: integer
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TodoEntity'
    delete:
      parameters:
      - name: id
        in: path
        required: true
        schema:
          format: int64
          type: integer
      responses:
        "204":
          description: No Content
components:
  schemas:
    TodoEntity:
      type: object
      properties:
        completed:
          type: boolean
        id:
          format: int64
          type: integer
        title:
          type: string
    ListTodoEntity:
      type: array
      items:
        $ref: '#/components/schemas/TodoEntity'