apiVersion: gloo.solo.io/v1
kind: UpstreamGroup
metadata:
  name: todo-service-group
  namespace: todo
spec:
  destinations:
  - destination:
      upstream:
        name: todo-todo-v1-8080
        namespace: todo
    weight: 8
  - destination:
      upstream:
        name: todo-todo-v2-8080
        namespace: todo
    weight: 2