apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: todo-prod
  namespace: todo
spec:
  virtualHost:
    domains:
    - todo.mattel-west.gsolo.net
    routes:
    - matchers:
      - prefix: /
      routeAction:
        upstreamGroup:
          name: todo-service-group
          namespace: todo