apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: todo-v1
    app.kubernetes.io/version: v1
  name: todo-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: todo-v1
      app.kubernetes.io/version: v1
  template:
    metadata:
      annotations:
        prometheus.io/port: "8080"
        prometheus.io/scheme: http
        prometheus.io/scrape: "true"
        prometheus.io/path: /actuator/prometheus
      labels:
        app.kubernetes.io/name: todo-v1
        app.kubernetes.io/version: v1
    spec:
      containers:
      - env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: murphye/quarkus-todo:1.0
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /actuator/health/live
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 0
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 10
        name: todo-v1
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /actuator/health/ready
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 0
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 10