apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "8080"
    prometheus.io/scheme: http
    prometheus.io/scrape: "true"
    prometheus.io/path: /actuator/prometheus
  labels:
    app.kubernetes.io/name: todo-v1
    app.kubernetes.io/version: v1
  name: todo-v1
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/name: todo-v1
    app.kubernetes.io/version: v1
  type: ClusterIP