apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: todo-v2
    app.kubernetes.io/version: v2
  name: todo-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: todo-v2
      app.kubernetes.io/version: v2
    metadata:
      labels:
        app.kubernetes.io/name: todo-v2
        app.kubernetes.io/version: v2
    spec:
      containers:
      - env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: murphye/quarkus-todo:2.0
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /actuator/health/live
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 0
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 10
        name: todo-v2
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /actuator/health/ready
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 0
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 10
