apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: todo-bg
  namespace: gloo-system
spec:
  virtualHost:
    domains:
    - todo.mattel-west.gsolo.net
    routes:
    - matchers:
      - prefix: /
      routeAction:
        single:
          upstream:
            name: todo-service-group
            namespace: gloo-system