apiVersion: devportal.solo.io/v1alpha1
kind: Portal
metadata:
  name: todo-portal
  namespace: todo
spec:
  displayName: Todo Portal
  description: The Portal for the Todo API
  banner:
    fetchUrl: https://www.annualreports.com/HostedData/CompanyHeader/NASDAQ_MAT.jpg
  favicon:
    fetchUrl: https://www.mattel.com/content/dam/corp-site/logos-and-icons/favicon/Mattel_logo_favicon.png
  primaryLogo:
    fetchUrl: https://www.mattel.com/content/dam/corp-site/logos-and-icons/Mattel-Logo-Nav_Desktop_Shadow.png
  customStyling: {}
  staticPages: []

  domains:
  - todo-portal.mattel-east.gsolo.net
  - todo-portal.mattel-west.gsolo.net

  # This will include all API product of the environment in the portal
  publishedEnvironments:
  - name: todo
    namespace: todo